"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ColorPicker } from "@/components/ui/color-picker";
import { ThemePresetCard } from "@/components/ui/theme-preset-card";
import type { ProductTheme } from "@/lib/models/product-theme";

const defaultTheme: ProductTheme = {
  theme_id: "", // Default value, will be generated by DB
  product_id: "", // Default value, will be set when linked to a product
  primary_bg_color: "#ffffff",
  secondary_bg_color: "#f44336",
  accent_bg_color: "#ffc107",
  primary_text_color: "#333333",
  secondary_text_color: "#666666",
  accent_text_color: "#ffc107",
  link_color: "#3182ce",
  link_hover_color: "#2c5282",
  primary_button_bg: "#ff5722",
  primary_button_text: "#ffffff",
  primary_button_hover_bg: "#f44336",
  secondary_button_bg: "#e0e0e0",
  secondary_button_text: "#333333",
  secondary_button_hover_bg: "#bdbdbd",
  card_bg_color: "#ffffff",
  card_border_color: "#e0e0e0",
  card_shadow_color: "#0000001a",
  header_bg_color: "#ffffff",
  header_text_color: "#111111",
  footer_bg_color: "#333333",
  footer_text_color: "#ffffff",
  font_family: "Inter, sans-serif",
  h1_font_size: "2.5rem",
  h1_font_weight: "700",
  h2_font_size: "2rem",
  h2_font_weight: "600",
  h3_font_size: "1.5rem",
  h3_font_weight: "500",
  body_font_size: "1rem",
  body_line_height: "1.5",
  section_padding: "2rem",
  card_padding: "1.5rem",
  button_padding: "0.75rem 1.5rem",
  border_radius_sm: "4px",
  border_radius_md: "8px",
  border_radius_lg: "12px",
  border_radius_xl: "16px",
  max_width: "1200px",
  container_padding: "1rem",
  gradient_start: "",
  gradient_end: "",
  shadow_color: "",
  custom_css: "",
};

const presetThemes = [
  {
    name: "Default",
    theme: defaultTheme,
  },
  {
    name: "Dark",
    theme: {
      ...defaultTheme,
      primary_bg_color: "#121212",
      secondary_bg_color: "#1e1e1e",
      primary_text_color: "#e0e0e0",
      secondary_text_color: "#bdbdbd",
      card_bg_color: "#1e1e1e",
      card_border_color: "#333333",
      header_bg_color: "#1e1e1e",
      header_text_color: "#ffffff",
      footer_bg_color: "#000000",
      footer_text_color: "#e0e0e0",
    },
  },
  {
    name: "Ocean Blue",
    theme: {
      ...defaultTheme,
      primary_bg_color: "#0ea5e9",
      secondary_bg_color: "#0284c7",
      accent_bg_color: "#38bdf8",
      primary_text_color: "#ffffff",
      secondary_text_color: "#e0f2fe",
      primary_button_bg: "#f59e0b",
      header_bg_color: "#0284c7",
      footer_bg_color: "#075985",
    },
  },
  {
    name: "Forest Green",
    theme: {
      ...defaultTheme,
      primary_bg_color: "#059669",
      secondary_bg_color: "#047857",
      accent_bg_color: "#10b981",
      primary_text_color: "#ffffff",
      secondary_text_color: "#d1fae5",
      primary_button_bg: "#dc2626",
      header_bg_color: "#047857",
      footer_bg_color: "#064e3b",
    },
  },
  {
    name: "Sunset Orange",
    theme: {
      ...defaultTheme,
      primary_bg_color: "#ea580c",
      secondary_bg_color: "#dc2626",
      accent_bg_color: "#f97316",
      primary_text_color: "#ffffff",
      secondary_text_color: "#fed7aa",
      primary_button_bg: "#1d4ed8",
      header_bg_color: "#dc2626",
      footer_bg_color: "#991b1b",
    },
  },
  {
    name: "Royal Purple",
    theme: {
      ...defaultTheme,
      primary_bg_color: "#7c3aed",
      secondary_bg_color: "#6d28d9",
      accent_bg_color: "#8b5cf6",
      primary_text_color: "#ffffff",
      secondary_text_color: "#e9d5ff",
      primary_button_bg: "#f59e0b",
      header_bg_color: "#6d28d9",
      footer_bg_color: "#581c87",
    },
  },
];

interface ThemeCustomizerProps {
  initialTheme?: ProductTheme;
  onChange: (theme: ProductTheme) => void;
}

export function ThemeCustomizer({
  initialTheme = defaultTheme,
  onChange,
}: ThemeCustomizerProps) {
  const [theme, setTheme] = useState<ProductTheme>(
    initialTheme || defaultTheme
  );
  const [selectedPreset, setSelectedPreset] = useState<string>("Default");

  const handleChange = (key: keyof ProductTheme, value: string) => {
    const updatedTheme = { ...theme, [key]: value };
    setTheme(updatedTheme);
    onChange(updatedTheme);
    setSelectedPreset(""); // Clear preset selection when manually changing colors
  };

  const applyPreset = (presetTheme: ProductTheme, presetName: string) => {
    const mergedTheme = { ...theme, ...presetTheme };
    setTheme(mergedTheme);
    onChange(mergedTheme);
    setSelectedPreset(presetName);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>🎨 Theme Customization</CardTitle>
        <CardDescription>
          Choose from beautiful preset themes or customize your own colors to
          match your brand
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="presets">
          <TabsList className="mb-6">
            <TabsTrigger value="presets">🌟 Preset Themes</TabsTrigger>
            <TabsTrigger value="colors">🎨 Custom Colors</TabsTrigger>
            <TabsTrigger value="typography">✍️ Typography</TabsTrigger>
            <TabsTrigger value="preview">👀 Preview</TabsTrigger>
          </TabsList>

          <TabsContent value="presets">
            <div className="space-y-4">
              <div className="text-sm text-gray-600 mb-4">
                Choose from our professionally designed color themes or
                customize your own colors in the Custom Colors tab.
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {presetThemes.map((preset) => (
                  <ThemePresetCard
                    key={preset.name}
                    theme={preset.theme}
                    name={preset.name}
                    isSelected={selectedPreset === preset.name}
                    onClick={() => applyPreset(preset.theme, preset.name)}
                  />
                ))}
              </div>
            </div>
          </TabsContent>

          <TabsContent value="colors">
            <div className="space-y-6">
              <div className="text-sm text-gray-600 mb-4">
                Customize individual colors for your product page. Changes here
                will override preset selections.
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                    🌈 Background Colors
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ColorPicker
                      label="Primary Background"
                      value={theme.primary_bg_color}
                      onChange={(color) =>
                        handleChange("primary_bg_color", color)
                      }
                    />
                    <ColorPicker
                      label="Secondary Background"
                      value={theme.secondary_bg_color}
                      onChange={(color) =>
                        handleChange("secondary_bg_color", color)
                      }
                    />
                    <ColorPicker
                      label="Accent Background"
                      value={theme.accent_bg_color}
                      onChange={(color) =>
                        handleChange("accent_bg_color", color)
                      }
                    />
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                    ✍️ Text Colors
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ColorPicker
                      label="Primary Text"
                      value={theme.primary_text_color}
                      onChange={(color) =>
                        handleChange("primary_text_color", color)
                      }
                    />
                    <ColorPicker
                      label="Secondary Text"
                      value={theme.secondary_text_color}
                      onChange={(color) =>
                        handleChange("secondary_text_color", color)
                      }
                    />
                    <ColorPicker
                      label="Accent Text"
                      value={theme.accent_text_color}
                      onChange={(color) =>
                        handleChange("accent_text_color", color)
                      }
                    />
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                    🔘 Button Colors
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ColorPicker
                      label="Primary Button Background"
                      value={theme.primary_button_bg}
                      onChange={(color) =>
                        handleChange("primary_button_bg", color)
                      }
                    />
                    <ColorPicker
                      label="Primary Button Text"
                      value={theme.primary_button_text}
                      onChange={(color) =>
                        handleChange("primary_button_text", color)
                      }
                    />
                    <ColorPicker
                      label="Secondary Button Background"
                      value={theme.secondary_button_bg}
                      onChange={(color) =>
                        handleChange("secondary_button_bg", color)
                      }
                    />
                    <ColorPicker
                      label="Secondary Button Text"
                      value={theme.secondary_button_text}
                      onChange={(color) =>
                        handleChange("secondary_button_text", color)
                      }
                    />
                  </div>
                </div>

                <div>
                  <h3 className="text-lg font-medium mb-4 flex items-center gap-2">
                    🏷️ UI Elements
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ColorPicker
                      label="Card Background"
                      value={theme.card_bg_color}
                      onChange={(color) => handleChange("card_bg_color", color)}
                    />
                    <ColorPicker
                      label="Card Border"
                      value={theme.card_border_color}
                      onChange={(color) =>
                        handleChange("card_border_color", color)
                      }
                    />
                    <ColorPicker
                      label="Header Background"
                      value={theme.header_bg_color}
                      onChange={(color) =>
                        handleChange("header_bg_color", color)
                      }
                    />
                    <ColorPicker
                      label="Header Text"
                      value={theme.header_text_color}
                      onChange={(color) =>
                        handleChange("header_text_color", color)
                      }
                    />
                    <ColorPicker
                      label="Footer Background"
                      value={theme.footer_bg_color}
                      onChange={(color) =>
                        handleChange("footer_bg_color", color)
                      }
                    />
                    <ColorPicker
                      label="Footer Text"
                      value={theme.footer_text_color}
                      onChange={(color) =>
                        handleChange("footer_text_color", color)
                      }
                    />
                  </div>
                </div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="typography">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="font_family">Font Family</Label>
                <select
                  id="font_family"
                  value={theme.font_family}
                  onChange={(e) => handleChange("font_family", e.target.value)}
                  className="w-full p-2 border rounded-md"
                >
                  <option value="Inter, sans-serif">Inter</option>
                  <option value="Arial, sans-serif">Arial</option>
                  <option value="Helvetica, sans-serif">Helvetica</option>
                  <option value="Georgia, serif">Georgia</option>
                  <option value="Times New Roman, serif">
                    Times New Roman
                  </option>
                  <option value="Roboto, sans-serif">Roboto</option>
                  <option value="Open Sans, sans-serif">Open Sans</option>
                </select>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="h1_font_size">H1 Font Size</Label>
                  <Input
                    id="h1_font_size"
                    type="text"
                    value={theme.h1_font_size}
                    onChange={(e) =>
                      handleChange("h1_font_size", e.target.value)
                    }
                    placeholder="2.5rem"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="h1_font_weight">H1 Font Weight</Label>
                  <select
                    id="h1_font_weight"
                    value={theme.h1_font_weight}
                    onChange={(e) =>
                      handleChange("h1_font_weight", e.target.value)
                    }
                    className="w-full p-2 border rounded-md"
                  >
                    <option value="400">Normal</option>
                    <option value="500">Medium</option>
                    <option value="600">Semi Bold</option>
                    <option value="700">Bold</option>
                    <option value="800">Extra Bold</option>
                  </select>
                </div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="preview">
            <div className="space-y-4">
              <h3 className="text-lg font-medium mb-4">Live Preview</h3>
              <div
                className="p-6 rounded-lg border-2"
                style={{
                  backgroundColor: theme.primary_bg_color,
                  color: theme.primary_text_color,
                  fontFamily: theme.font_family,
                  borderColor: theme.card_border_color,
                }}
              >
                <h1
                  style={{
                    fontSize: theme.h1_font_size,
                    fontWeight: theme.h1_font_weight,
                    color: theme.header_text_color,
                    marginBottom: "1rem",
                  }}
                >
                  Your Product Title
                </h1>
                <p
                  style={{
                    color: theme.secondary_text_color,
                    marginBottom: "1.5rem",
                  }}
                >
                  This is how your product description will look with the
                  current theme settings.
                </p>
                <div className="flex gap-3">
                  <button
                    style={{
                      backgroundColor: theme.primary_button_bg,
                      color: theme.primary_button_text,
                      padding: theme.button_padding,
                      borderRadius: theme.border_radius_sm,
                      border: "none",
                      cursor: "pointer",
                    }}
                  >
                    Primary Button
                  </button>
                  <button
                    style={{
                      backgroundColor: theme.secondary_button_bg,
                      color: theme.secondary_button_text,
                      padding: theme.button_padding,
                      borderRadius: theme.border_radius_sm,
                      border: "none",
                      cursor: "pointer",
                    }}
                  >
                    Secondary Button
                  </button>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
