-- Create reviews table
CREATE TABLE reviews (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id VARCHAR2(255) NOT NULL,
  name VARCHAR2(255) NOT NULL,
  address VARCHAR2(500) NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text CLOB NOT NULL,
  avatar VARCHAR2(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

-- Create index for product_id
CREATE INDEX idx_product_id ON reviews(product_id);

-- Add some sample reviews (optional)
-- Add some sample reviews (optional)
INSERT INTO reviews (product_id, name, address, rating, review_text) VALUES
('sample-product-id', 'Michael R.', '42, New York, NY', 5, 'I''ve been using this product for 3 weeks, and the results are amazing! It gave me the energy and confidence I needed. My workouts are more productive and I feel stronger than ever.'),
('sample-product-id', 'David T.', '38, Los Angeles, CA', 5, 'I''m amazed by how quickly I felt the difference. My workouts are better, and my energy levels have skyrocketed! I''ve tried other supplements before, but nothing compares to this product.'),
('sample-product-id', 'James K.', '45, Chicago, IL', 4, 'After trying several products, this is the only one that delivered real results. Highly recommended! I''ve noticed significant improvements in just two weeks of use.');
